eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gatewayapplication
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Author
          uri: http://localhost:8989
          predicates:
            - Path=/api/v2/**

        - id: Authentication-Service
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**
          
        - id: book-service
          uri: http://localhost:5959
          predicates:
            - Path=/api/**



