eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver-sr:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Author
          uri: http://localhost:8989
          predicates:
            - Path=/api/v1/**
          filters:
#            - AuthenticationFilter
        - id: book-service
          uri: http://localhost:5959
          predicates:
            - Path=/api/**
          filters:
#            - AuthenticationFilter
        - id: AuthenticationService
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/**

